services:
  - type: web
    name: community-hub-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        scope: build
      - key: JWT_SECRET
        scope: build
      - key: JWT_EXPIRE
        value: 1h
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        scope: build
      - key: NODE_ENV
        value: production
